### PR TITLE
Duplicates databricks article temporarily

### PR DESCRIPTION
**Pull request by AlexandreSajus**
We are listed on the Databricks website as a technology partner:
image

Unfortunately, since the 4.0 release, we changed the URL structure of our docs, and clicking on Taipy on the [Databricks website](https://www.databricks.com/company/partners/technology) now redirects to a 404 error page: https://docs.taipy.io/en/latest/tutorials/integration/4_databricks/

The correct URL is now: https://docs.taipy.io/en/latest/tutorials/articles/databricks/

This PR duplicates the Databricks article to make it available at the old URL. This way, clicking on Taipy on the Databricks website will redirect to the article.

This is a temporary change. I have emailed our contact at Databricks, asking them to change our URL on their website to the correct, new one. It's 3 AM here. I took 4mg of melatonin and still can't sleep, so I am opening this PR to pass the time. Did you know that GitHub supports DOOM faces as emojis? Take a look at this: :suspect: I was thinking of attaching my GoPro to my rifle, streaming the video to YouTube, and then looking at the stream through my VR headset. This way, you could shoot accurately from behind cover without having to expose yourself. I might do that now. Either that or I'll go to sleep.

### CODE REVIEW

**Comment by FlorianJacta** [comment]
Did you build the documentation and test it to ensure it was accessible?

**Comment by AlexandreSajus** [comment]
Yes, when I built the docs, the article was accessible with:
http://127.0.0.1:8000/en/develop/tutorials/integration/4_databricks/

**Review by FlorianJacta — APPROVED** [review]
LGTM

**Comment by jrobinAV** [comment]
Why on `develop` branch? We only need it temporarily in the `latest` branch, no?

**Comment by AlexandreSajus** [comment]
Yes, I thought the workflow to push to latest was that we had to push to develop first

**Comment by jrobinAV** [comment]
not if we don't want it into develop.

**Pull request merged**
