### PR TITLE
Adds a demo: a chatbot that supports image inputs using GPT-4o

### PR DESCRIPTION
**Pull request by AlexandreSajus**
Adds a new vision chatbot demo:
image

Test the demo [here](https://gpt-4o-chat.taipy.cloud/)

### CODE REVIEW

**Comment by FlorianJacta** [comment]
Is it the last demo/card on the LLM index page?

**Comment by AlexandreSajus** [comment]
> Is it the last demo/card on the LLM index page?

It's the third out of five:
image

**Comment by FlorianJacta** [comment]
This is the wrong order. The navigation on the left and the cards don't have the same order

**Comment by AlexandreSajus** [comment]
Fixed the order issue:
image

**Review by FlorianJacta — APPROVED** [review]

**Pull request merged**
