### PR TITLE
Removes deployment docs

### PR DESCRIPTION
**Pull request by AlexandreSajus**
Removes documentation about deployment:
image

### CODE REVIEW

**Review by jrobinAV — COMMENTED** [review]
It does not make much sense to me.

**Comment by FlorianJacta** [comment]
This does not align with https://github.com/Avaiga/taipy-enterprise/issues/406, where a discussion should be done.

**Comment by AlexandreSajus** [comment]
I'll change the message to something like "The doc is available by contacting us. Taipy Enterprise provides..."
I'll also keep the deployment pages as described in here: https://github.com/Avaiga/taipy-enterprise/issues/406

**Comment by AlexandreSajus** [comment]
Closing this PR, I made a new one here: https://github.com/Avaiga/taipy-doc/pull/1035

**Pull request closed without merging**
