### PR TITLE
feat(css): align quick access card title and icon

### PR DESCRIPTION
**Pull request by ghost**
Following a demand from Vincent, align the title and icon in quick access cards.

### CODE REVIEW

**Review by FabienLelaquais — APPROVED** [review]
👌

**Review by jrobinAV — COMMENTED** [review]
approved!

**Comment by jrobinAV** [comment]
don't forget to delete branch when it s done.

**Comment by ghost** [comment]
> don't forget to delete branch when it s done.

You're right, my bad. I use to do it, but I forgot here.

**Pull request merged**
