### PR TITLE
Propagates decimator tutorial tgb approach to latest

### PR DESCRIPTION
**Pull request by AlexandreSajus**
image

### CODE REVIEW

**Review by FlorianJacta — APPROVED** [review]
LGTM

**Comment by FabienLelaquais** [comment]
@AlexandreSajus I really don't like this syntax.
We need to allow (and use) `decimator=decimator_instance` and *not* force the use of a variable.
I don't know if this works right away but I suspect it does.

**Comment by AlexandreSajus** [comment]
> @AlexandreSajus I really don't like this syntax. We need to allow (and use) `decimator=decimator_instance` and _not_ force the use of a variable. I don't know if this works right away but I suspect it does.

Unfortunately, the syntax you propose currently does not work both in Taipy latest and in Taipy develop. I just tested both.

**Comment by FabienLelaquais** [comment]
> > @AlexandreSajus I really don't like this syntax. We need to allow (and use) `decimator=decimator_instance` and _not_ force the use of a variable. I don't know if this works right away but I suspect it does.
> 
> Unfortunately, the syntax you propose currently does not work both in Taipy latest and in Taipy develop. I just tested both.

Thank you @AlexandreSajus. We MUST fix that. I have created [this issue](https://github.com/Avaiga/taipy/issues/1591).

**Pull request merged**
