### PR TITLE
Add commodity trading application

### LINKED ISSUE #1024: Add commodity trading application to Gallery
**Description**
Add Commodity Trading application to Gallery.

**Expected change**
We should :

- [x] Create a private repo for this application following the demo template,
- [x] Create a Readme file for this repo
- [x] Deploy the application
- [x] Integrate the application to the gallery
- [x] Describe the entire application in its page in the gallery

### PR DESCRIPTION
**Pull request by FlorianJacta**
Resolves #1024 

The application has been deployed: https://commodity-trading.taipy.cloud/

The repository has been created: 

Question: What should be the position of the application?

image

image

image

image

[Commodity Trading - Taipy (2).zip](https://github.com/user-attachments/files/16172791/Commodity.Trading.-.Taipy.2.zip)

### CODE REVIEW

**Review by AlexandreSajus — CHANGES_REQUESTED** [review]
Consider adding a prominent disclaimer that the data behind the app has been mocked, so interacting with the app does nothing. We don't want people trying out the app and thinking Taipy is buggy because nothing happens when changing the date.

Third in the finance category is a good position

**Comment by FlorianJacta** [comment]
@AlexandreSajus I didn't know it changed nothing. I think this is bad... We should create fake data and have the interactions working. What do you think?

**Comment by AlexandreSajus** [comment]
It's your call, it's a lot of fake data to generate so we could generate it randomly. Or we could just explain that there is no interaction because this is a mock application.

**Comment by FlorianJacta** [comment]
An "Enterprise" application shouldn't be in this state.

**Comment by FlorianJacta** [comment]
Blocked by creating interaction in application.

**Comment by FlorianJacta** [comment]
What do you think of it now? https://commodity-trading.taipy.cloud/
@AlexandreSajus

**Comment by AlexandreSajus** [comment]
It is an improvement, but some pages still don't have interaction like this one:
https://commodity-trading.taipy.cloud/group_contributions
Is this intended?

**Comment by FlorianJacta** [comment]
Zacch didn't bring interactivity to these pages: https://github.com/Avaiga/demo-commodity-trading/pull/9

They should come later. I propose to make their buttons/date inactive.

**Comment by FlorianJacta** [comment]
This is done. Viz elements are inactive if they don't bring interactivity.

**Review by AlexandreSajus — APPROVED** [review]
Perfect, looks good to me!

**Pull request merged**
