### PR TITLE
Add Taipy Studio GIF

### LINKED ISSUE #744: Taipy Studio is almost non-existent in the doc
**Description**
Taipy Studio is not mentioned until the Scenario Management tutorial which comes quite late in the learning journey of Taipy. We should probably add a comment with an image at the beginning of the GUI tutorial so that new users get at least the completion capabilities of Taipy Studio.

**Expected change**
In the beginning of the GUI tutorial. Add a sentence like "If you have VSCode, you can install Taipy Studio, our VSCode extension that provides completions for Taipy code and allows you to edit data pipelines in a graph based editor"
With an image like:
image

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Related Issue 
Fixed #744 

## Updates
- Added Taipy Studio GIF to the repo and displayed it on the "Understanding GUI" page.

## Screenshot 
taipy-studio-section

### CODE REVIEW

**Comment by FlorianJacta** [comment]
There are two runs in the GIF, which is confusing. Could you make another GIF with the Markdown text and the *run* after?

**Comment by Satoshi-Sh** [comment]
I replaced it with this.

taipy-studio-ezgif com-cut

P.S. @FlorianJacta Let me know if you have something else to update.

**Comment by Satoshi-Sh** [comment]
Any updates on this PR? @FlorianJacta

**Comment by FlorianJacta** [comment]
Sorry, I was on holiday. I don't understand why you have two `run` methods in the GIF. I would prefer if we could see the full string also.

**Comment by Satoshi-Sh** [comment]
No problem. I misunderstood your first comment. I will update it soon.

*P.S.*
This is an updated GIF.
taipystudio-demo

**Comment by FlorianJacta** [comment]
This looks great!

**Review by FlorianJacta — APPROVED** [review]

**Pull request merged**
