### PR TITLE
Document the chat control

### PR DESCRIPTION
**Pull request by FabienLelaquais**
Addresses #971.
- Documentation and examples for the chat control.
- Reorganize Release Notes for Taipy 4.0 (3.0 moved to Legacy).
- Section on shared variables
- Release Notes for pull requests #1092 and #1598.
- Fix generation of crossrefs to Reference Manuals

### CODE REVIEW

**Review by AlexandreSajus — COMMENTED** [review]
Great examples! They are a bit complex, so make sure to include the complete code somewhere or at least the imports (for Icon, for example). Examples of styling and adding the tgb syntax would also be helpful.

I don't know if I can approve this PR since it modifies many files. Why is it modifying the chatbot tutorial. Shouldn't this be done in a separate PR?

**Comment by FabienLelaquais** [comment]
> Great examples! They are a bit complex, so make sure to include the complete code somewhere or at least the imports (for Icon, for example). Examples of styling and adding the tgb syntax would also be helpful.
> 
> I don't know if I can approve this PR since it modifies many files. Why is it modifying the chatbot tutorial. Shouldn't this be done in a separate PR?

Thanks @AlexandreSajus!
- The examples are provided as complete scripts that you can download directly from GitHub.
- I may spend some time rewriting the page definitions in tgb if I have time.
- The chatbot tutorial is modified because it does not use the same conventions as the rest of the doc. When I spot problems like that, I modify them. For example, referencing a function should always use the '*' style and the parenthesis.
- You can approve what you have seen and agreed on, even if it's not complete. The other team members are reviewers.

**Comment by AlexandreSajus** [comment]
> Great examples! They are a bit complex, so make sure to include the complete code somewhere or at least the imports (for Icon, for example). Examples of styling and adding the tgb syntax would also be helpful.
> 
> I don't know if I can approve this PR since it modifies many files. Why is it modifying the chatbot tutorial. Shouldn't this be done in a separate PR?

Understood, I will only review the chat control doc page. From a reader standpoint, I did not see a way to get the complete code for the examples, so I copy-pasted the snippets of the code you provided. This generated errors because I did not have imports. Some imports are easy to fix for a beginner, but others, like Icon, are not. This led me to remove all mentions of "Icon" from the code. There should be a straightforward way to get the full code somewhere.

**Comment by FabienLelaquais** [comment]
> Understood, I will only review the chat control doc page. From a reader standpoint, I did not see a way to get the complete code for the examples, so I copy-pasted the snippets of the code you provided.
For more examples, when you enter the example section, you have a link ("You can download the entire source code... blabla") that takes you straight to the code.
I'm surprised you didn't see that before.

**Comment by AlexandreSajus** [comment]
> > Understood, I will only review the chat control doc page. From a reader standpoint, I did not see a way to get the complete code for the examples, so I copy-pasted the snippets of the code you provided.
> > For more examples, when you enter the example section, you have a link ("You can download the entire source code... blabla") that takes you straight to the code.
> > I'm surprised you didn't see that before.

Look, I missed it while reading the page, so I can guarantee "Random Python Beginner 21 who wants to do an LLM chatbot despite only 2 months of experience" will miss it:
image
If you want to merge this, go ahead. But I guarantee you, without a code snippet for the imports, someone will fail when trying to reproduce the example

**Comment by FabienLelaquais** [comment]
> without a code snippet for the imports

That's why we provide it. May be a visible icon of some sort will help.
We've had that since 3.0 at least. I'm still amazed you did not spot it.
Thanks

**Comment by AlexandreSajus** [comment]
> > without a code snippet for the imports
> 
> That's why we provide it. May be a visible icon of some sort will help. We've had that since 3.0 at least. I'm still amazed you did not spot it. Thanks

A visible icon would work, too, something that makes this information stand out among the rest of the text

**Review by dinhlongviolin1 — APPROVED** [review]
LGTM

**Pull request merged**
