### PR TITLE
Propose core quick access buttons

### PR DESCRIPTION
**Pull request by jrobinAV**
Hello, 

I finally had time to propose quick access buttons for Core features.

Please tell me what you thnk.

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
I don't know what to think about this.
On one hand, I find it visually satisfying, but on the other hand, I think the pills should be used for more self-explainatory features.
From an accessibility perspective, having to hover a pill to see what it is about is not suitable as some important info is hidden by default.
At the risk of charging the page a little more, maybe I would have used a lighter version of the card component from quick access above...

**Comment by jrobinAV** [comment]
I believed it was self-explanatory. If it s not, what about my new proposal?

**Review by ghost — CHANGES_REQUESTED** [review]
Yeah, seems way better to me, indeed.
Maybe now you don't even need the `tp-tooltip` anymore, as it is mostly just redundant with the pill label.

**Comment by jrobinAV** [comment]
Done

**Review by ghost — APPROVED** [review]
OK. Fine by me :)

**Comment by jrobinAV** [comment]
@vhfgosselin @FlorianJacta Any feedback?

**Pull request merged**
