### PR TITLE
Fix broken links in tutorials

### PR DESCRIPTION
**Pull request by FlorianJacta**
Fix broken links in tutorials

### CODE REVIEW

**Review by AlexandreSajus — APPROVED** [review]
Approved

**Review by jrobinAV — CHANGES_REQUESTED** [review]
This is on release 3.0. We MUST build the documentation to test before merging it. I need some time to build it.
Until someone can build the doc (a screenshot as a proof) or until I got the time, I block the PR.

**Comment by FlorianJacta** [comment]
No worries, I wasn't going to merge it this time

**Review by jrobinAV — APPROVED** [review]
I finally got the time to build the doc.
Looks good to me!

**Pull request merged**
